### ISSUE TITLE
doesn't work on touch screen

### ISSUE THREAD

**Issue by fattypiggy** [mazdik/ng-modal#1]
device: Android 6.0 tablet
browser: Chrome 68

**Comment by mazdik** [comment]
[support for touch-based user interfaces](https://github.com/mazdik/ng-modal/commit/4a16dd02ba8bf11b3085f2951852f45c5bf20c85)
need to test

**Comment by fattypiggy** [comment]
@mazdik I commented you, you can have a check. [link](https://github.com/mazdik/ng-modal/commit/4a16dd02ba8bf11b3085f2951852f45c5bf20c85#r30398052)

**Comment by mazdik** [comment]
ok [parseFloat](https://github.com/mazdik/ng-modal/commit/083e018f3f341c914433b96343c4df93e6da68fb)

**Comment by fattypiggy** [comment]
@mazdik great, thanks.
