### ISSUE TITLE
css issue for angular cli 9.2.1

### ISSUE THREAD

**Issue by XsiSec** [mazdik/ng-modal#14]
Hello Dear I cant make the css working in angular cli 9.2.1

![image](https://user-images.githubusercontent.com/17006430/85064058-4f871c00-b1ab-11ea-8a67-331fb1c8c393.png)

![image](https://user-images.githubusercontent.com/17006430/85064092-5a41b100-b1ab-11ea-86cc-bec6361277f1.png)

the header is still primary blue

![image](https://user-images.githubusercontent.com/17006430/85064212-82c9ab00-b1ab-11ea-9e87-e1b2ade40e62.png)

atempt 2 with nested modal:

![image](https://user-images.githubusercontent.com/17006430/85064740-4c406000-b1ac-11ea-939d-439b115ad326.png)

![image](https://user-images.githubusercontent.com/17006430/85064802-65e1a780-b1ac-11ea-81fc-f079b060216a.png)

I have tried now in almost a week to solve this but I cant.

Notice my style.scss is clean as well.

**Comment by mazdik** [comment]
encapsulation: ViewEncapsulation.None,
have you tried this?

**Comment by XsiSec** [comment]
yup that was the issue!
