### ISSUE TITLE
Do you have the plan to refactor the code into Angular style?

### ISSUE THREAD

**Issue by fattypiggy** [mazdik/ng-modal#2]
Firstly, I like your component:).

As the title said, I have checked your codes, and found that in the ng-modal component, you use `addEventListener` way, not Angular `@HostListener` style to bind handler, so do you want to have a update about that?

And I have forked your repo into my local computer, changed it into Angular style, but found that if you drag the modal move it so fast, the performance is not as good as yours, can you explain that for me? 

thank you very much.

**Comment by mazdik** [comment]
What is bad addEventListener? ) ngZone.runOutsideAngular - so you can run a native addEventListener outside angular

**Comment by fattypiggy** [comment]
Actually, I don't know what is bad using addEventListener, just think using decorator looks more like Angular style. No problem, this component behaves very well.
