### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by floatas** [mazdik/ng-modal#3]
Hi, is this library available as npm package ?

**Comment by mazdik** [comment]
No, I did not add

**Comment by mazdik** [comment]
npm i ng-mazdik-lib --save
import {ModalModule} from 'ng-mazdik-lib';

**Comment by Mukeshkotti** [comment]
In mobile not able to drag and resize?

**Comment by jCzachor6** [comment]
Hi,
could you please add this modal as an npm package, this one is truly great, but all the other components are not needed for my project.

**Comment by mazdik** [comment]
added
npm i ng-modal-lib --save
