### ISSUE TITLE
It is possible?

### ISSUE THREAD

**Issue by Corralini** [mazdik/ng-modal#5]
Hello, my name is Alejandro and i have a question, it is possible make the modal open by default?
Let me explain, i want open the modal when the application start, like a welcome message or something similar.

Thanks,
Alejandro Corral

**Comment by mazdik** [comment]
```js
@ViewChild('childModal', {static: false}) childModal: ModalComponent;
ngAfterViewInit() {
  this.childModal.show();
  this.childModal.hide();
}
```

**Comment by Corralini** [comment]
> ```js
> @ViewChild('childModal', {static: false}) childModal: ModalComponent;
> ngAfterViewInit() {
>   this.childModal.show();
>   this.childModal.hide();
> }
> ```
> 
> <app-modal #childModal

Thanks a lot.
