### ISSUE TITLE
Not working in mobile.

### ISSUE THREAD

**Issue by Mukeshkotti** [mazdik/ng-modal#6]
not able to drag and resize in mobile.

I have imported "ng-mazdik-lib" module

**Comment by mazdik** [comment]
What version of mobile OS?
try the latest version from git

**Comment by Mukeshkotti** [comment]
In git clone I am not able to close modal popup. 

Please check the attachment

in live link (https://mazdik.github.io/ng-modal/) it is working perfectly

![Uploading localscreen.PNG…]()
![livescreen](https://user-images.githubusercontent.com/48877082/70290960-af196d80-17ff-11ea-9f27-4cf8ab8aceb3.PNG)

**Comment by mazdik** [comment]
[fixed](https://github.com/mazdik/ng-modal/commit/5c38eccaa10cf4766b5d5178d07c3d48035e8245)

**Comment by Mukeshkotti** [comment]
Thanks for your quick update, It is working.
