### ISSUE TITLE
[help] How do you use the draggable modals ?

### ISSUE THREAD

**Issue by borisBelloc** [mazdik/ng-modal#8]
Hello,

I installed the package `npm i ng-modal-lib --save`

but I don't understand how to use the modal ?

in the exemple html code, there is code like 
`(closeModal)="onCloseModal()">` 
 `(click)="modalRoot.hide()"` [...]

How do you define the methods it in the xxx.component.ts file ?
 I don't find any infos on the repository and I don't understand how the snippet could work without definition.

Thank you

Regards

**Comment by mazdik** [comment]
[sample](https://github.com/mazdik/ng-modal/blob/master/src/app/modal-demo.component.tsl)

**Comment by borisBelloc** [comment]
thank you for your reply, 

I still have problem with the  `<app-modal` from [source at lane 7](https://github.com/mazdik/ng-modal/blob/master/src/app/modal-demo.component.ts)

Angular told me that it's an unknow because of no definition... (yes i'm noob at angular)

For exemple [here](https://github.com/mazdik/ng-modal/blob/master/src/app/modal-demo.component.ts) we declare `app-modal-demo` but I have no clue where we declare `app-modal`  I checked the 7 files and didn't find any clue.

It's late, 😴 I will take more time tomorow to find how to use it.

**Comment by borisBelloc** [comment]
thank you for your reply, 

When I clone the repository it works, I will search how to make it work outside of it 😬
