### ISSUE TITLE
"export 'ModalComponent' was not found in 'ng-modal-lib'

### ISSUE THREAD

**Issue by wisespace-io** [mazdik/ng-modal#9]
I imported the module, but it is failing when I try to load the component

import { ModalComponent } from 'ng-modal-lib';

I am trying to import to be able to call "childModal.show" when an event happens.

@ViewChild('childModal', { static: false }) modal: ModalComponent;

**Comment by mazdik** [comment]
I forgot to export the component, I will add it later. For now, use type ANY

**Comment by mazdik** [comment]
added in version 0.0.3

**Comment by wisespace-io** [comment]
@mazdik I upgraded to version 0.0.3, but it is not building, I got the errors below

ERROR in ../node_modules/ng-modal-lib/lib/modal/modal.component.d.ts:39:9 - error TS1086: An accessor cannot be declared in an ambient context.

39     get dialogStyles(): {
           ~~~~~~~~~~~~
../node_modules/ng-modal-lib/lib/modal/modal.component.d.ts:42:9 - error TS1086: An accessor cannot be declared in an ambient context.

**Comment by mazdik** [comment]
As mentioned above, TypeScript 3.7 emits get/set accessors in .d.ts files which can cause breaking changes for consumers on older versions of TypeScript like 3.5 and prior. TypeScript 3.6 users will not be impacted, since that version was future-proofed for this feature.

**Comment by mazdik** [comment]
try new version 0.0.4

**Comment by wisespace-io** [comment]
@mazdik Thank you for fixing it.
